### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by Usernull-AI** [Mon4ik/homebridge-yandex#3]
Hello! Homebridge server startup fails due to the following error. `Error: Device "Насос" isn't supporting
    at CapabilityManager.getService (/var/lib/homebridge/node_modules/homebridge-yandex/src/capabilities/index.ts:119:23)
    at CapabilityManager.initAccessory (/var/lib/homebridge/node_modules/homebridge-yandex/src/capabilities/index.ts:35:30)
    at new CapabilityManager (/var/lib/homebridge/node_modules/homebridge-yandex/src/capabilities/index.ts:31:14)
    at YandexPlatform.configureAccessory (/var/lib/homebridge/node_modules/homebridge-yandex/src/platform.ts:98:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by Mon4ik** [comment]
Hello! Currently repository has a few supporting devices, and code is probably doesn't work :(

**Comment by Usernull-AI** [comment]
is there no way to exclude unsupported devices? for example, manually
6 июля 2023 г., 10:12 +0300, Дмитрий ***@***.***>, писал:

**Comment by Usernull-AI** [comment]
is there no way to exclude unsupported devices? for example, manually

**Comment by Usernull-AI** [comment]
Anyway, thanks for what you're doing. I look forward to the development of the project!

**Comment by mureev** [comment]
actually, there is an option to make all unsupported devices to be seen as a "socket" with only on/off action. If @Mon4ik is happy with this, I could add it. At least this is how I solved it while working on support for new devices.

**Comment by Mon4ik** [comment]
> actually, there is an option to make all unsupported devices to be seen as a [Switch](https://developers.homebridge.io/#/service/Switch) with only on/off action, as it seems to be universally supported action. If @Mon4ik is happy with this, I could add it.
> At least this is how I solved it while working on support for new devices.

Thank you for idea!
