### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'instance') after adding Яндекс Станция Миди to Home

### ISSUE THREAD

**Issue by pir0xy** [Mon4ik/homebridge-yandex#9]
After Homebridge restart its crashing

[11/22/2023, 7:35:03 PM] [Yandex SmartHome] Device "Яндекс Станция Миди 4FWT" isn't supporting (type: devices.types.smart_speaker.yandex.station.cucumber)
[ undefined ]
[11/22/2023, 7:35:04 PM] TypeError: Cannot read properties of null (reading 'instance')
    at Object.verify (/usr/local/lib/node_modules/homebridge-yandex/src/adapters/color_temperature.ts:9:19)
    at /usr/local/lib/node_modules/homebridge-yandex/src/adapters/index.ts:45:55
    at Array.filter (<anonymous>)
    at AdapterApplier.addAdapters (/usr/local/lib/node_modules/homebridge-yandex/src/adapters/index.ts:45:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/22/2023, 7:35:04 PM] Got SIGTERM, shutting down Homebridge...

**Comment by Mon4ik** [comment]
Попробуйте новую версию: https://github.com/Mon4ik/yandex-homekit
